### ISSUE TITLE
Coverage for remote_runtime.cc:196

### ISSUE THREAD

**Issue by no2chem** [vmware/cascade#50]
## Overview

- (x) **Bug report.** . The tests for remote_runtime.cc sometime do not run line 196, causing indeterministic coverage regressions

See https://codecov.io/gh/vmware/cascade/pull/48/changes

## Deliverables

- [x] Test cases should always cover line 196

**Comment by eschkufz** [comment]
See #29 --- 

I kind of want to get rid of this infrastructure altogether. It's complicating the codebase and it's enabling a functionality (running engines which are separated from the runtime by a network connection) which probably won't ever be performant.

This would mean getting rid of the remote family of testcases which is what's causing this to creep up. Since we'd be doing it eventually, why not just do it now and we'll gut the code to go along with it when we get to #29.
